In [71]:
import numpy as np
import pandas as pd

In [72]:
train_df = pd.read_csv("input/explicit-content-detection/train.csv")
# train_df['title'] = train_df['title'].str.replace(',','')
# train_df['title'] = train_df['title'].str.replace('-','')
# train_df['title'] = train_df['title'].str.replace('\"','')
# train_df['title'] = train_df['title'].str.replace('?','')
# train_df['title'] = train_df['title'].str.replace('!','')
# train_df['title'] = train_df['title'].str.replace('.','')
# train_df['title'] = train_df['title'].str.lower()
train_df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>url</th>
      <th>title</th>
      <th>target</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>m.kp.md</td>
      <td>Экс-министр экономики Молдовы - главе МИДЭИ, ц...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>www.kp.by</td>
      <td>Эта песня стала известна многим телезрителям б...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>fanserials.tv</td>
      <td>Банши 4 сезон 2 серия Бремя красоты смотреть о...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>colorbox.spb.ru</td>
      <td>Не Беси Меня Картинки</td>
      <td>False</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
      <td>tula-sport.ru</td>
      <td>В Новомосковске сыграют следж-хоккеисты алекси...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>135304</th>
      <td>135304</td>
      <td>mail.ru</td>
      <td>пора тюльпанов турецкий сериал на русском язык...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>135305</th>
      <td>135305</td>
      <td>www.ntv.ru</td>
      <td>Остросюжетный сериал «Шеф. Игра на повышение»....</td>
      <td>False</td>
    </tr>
    <tr>
      <th>135306</th>
      <td>135306</td>
      <td>topclassiccarsforsale.com</td>
      <td>1941 Plymouth Special Deluxe Hot Rod, Automati...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>135307</th>
      <td>135307</td>
      <td>wowcream.ru</td>
      <td>Купить It's Skin Сыворотка питательная Power 1...</td>
      <td>False</td>
    </tr>
    <tr>
      <th>135308</th>
      <td>135308</td>
      <td>www.ubu.ru</td>
      <td>Технический спирт в канистрах и флаконах, купи...</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
<p>135309 rows × 4 columns</p>
</div>

In [73]:
test_df = pd.read_csv("input/explicit-content-detection/test.csv")
# test_df['title'] = test_df['title'].str.replace(',','')
# test_df['title'] = test_df['title'].str.replace('-','')
# test_df['title'] = test_df['title'].str.replace('\"','')
# test_df['title'] = test_df['title'].str.replace('?','')
# test_df['title'] = test_df['title'].str.replace('!','')
# test_df['title'] = test_df['title'].str.replace('.','')
# test_df['title'] = test_df['title'].str.lower()
test_df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>url</th>
      <th>title</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>135309</td>
      <td>www.kommersant.ru</td>
      <td>Шестой кассационный суд в Самаре начнет работу...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>135310</td>
      <td>urexpert.online</td>
      <td>Что такое индексация алиментов, кем и в каких ...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>135311</td>
      <td>imperimeha.ru</td>
      <td>Женщинам | Империя Меха - Part 12</td>
    </tr>
    <tr>
      <th>3</th>
      <td>135312</td>
      <td>national-porn.com</td>
      <td>Небритые, волосатые киски: Порно всех стран и ...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>135313</td>
      <td>2gis.ru</td>
      <td>67</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>165373</th>
      <td>300682</td>
      <td>etp.armtek.ru</td>
      <td>Armtek - запчасти для грузовых и легковых авто...</td>
    </tr>
    <tr>
      <th>165374</th>
      <td>300683</td>
      <td>mail.ru</td>
      <td>Лилия Якупова - Караганда, Карагандинская обла...</td>
    </tr>
    <tr>
      <th>165375</th>
      <td>300684</td>
      <td>xn----8sbnqchpeeeth.xn--p1ai</td>
      <td>Администрация Лесного района Тверской области ...</td>
    </tr>
    <tr>
      <th>165376</th>
      <td>300685</td>
      <td>www-sunhome-ru.cdn.ampproject.org</td>
      <td>Сонник Изменение сознания. К чему снится Измен...</td>
    </tr>
    <tr>
      <th>165377</th>
      <td>300686</td>
      <td>virtual-hockey.org</td>
      <td>Строительство базы команды Гранд-Рапидс Гриффи...</td>
    </tr>
  </tbody>
</table>
<p>165378 rows × 3 columns</p>
</div>

In [74]:
X_train = train_df["title"].values
X_test = test_df["title"].values
y_train = train_df["target"].astype(int).values

In [75]:
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)

modelLR = LogisticRegression(solver = "liblinear", penalty='l2')

modelLR.fit(X_train_vectorized,y_train)
y_pred = modelLR.predict(X_train_vectorized)

f1_score(y_train, y_pred)

0.9749051291467744

In [76]:
X_test_vectorized = vectorizer.transform(X_test)

test_df["target"] = modelLR.predict(X_test_vectorized).astype(bool)
test_df[["id", "target"]].to_csv("ml_baseline.csv", index=False)

!cat ml_baseline.csv | head

id,target
135309,False
135310,False
135311,False
135312,True
135313,False
135314,False
135315,False
135316,False
135317,False
cat: stdout: Broken pipe